
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull

  pull_request_target:
    branches:
      - develop
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with: 
        args: >
          -Dsonar.organization=danieljacquin
          -Dsonar.projectKey=danieljacquin_todo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    if: github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.5.0'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run:  npm run build
    - uses: actions/upload-artifact@v2  
      with:
        name: dist
        path: dist

  test:
    if: github.event.pull_request.base.ref == 'develop'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '16.5.0'
    - name: Install dependencies
      run: npm ci
    - uses: actions/download-artifact@v2  
      with:
        name: dist
        path: dist
    - name: Test
      run:  npm run test

  deploy:
    if: github.event.pull_request.base.ref == 'main'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
