

name: SonarCloud-scan

on:
  Push:
    branches:
      - "develop"
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
  SonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2
          fetch-depth: 0 #Shallow clones should be disabled for a better relevancy analysis
      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
