  # video from midudev's youtube channel
  # https://www.youtube.com/watch?v=sIhm4YOMK6Q&list=WL&index=122&t=6181s
  # Github action  sonarcloud we used to do our workflow 
  # https://github.com/marketplace/actions/sonarcloud-scan

name: CI/CD

on:
  push:
    branches-ignore:
      - main
      - develop

  pull_request_target:
    branches:
      - develop
      - main

jobs:
  sonarcloud:
    if: github.event.pull_request.base.ref != 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with: 
        args: >
          -Dsonar.organization=danieljacquin
          -Dsonar.projectKey=danieljacquin_todo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

 